# Statistics: means the science of collecting data or information fot analysis which can be represented graphically or in chart

2 Major Types of Statistics
 - Inferential Statistics
 - Descriptive Statistics
  
  # Inferential Statistics makes prediction or conclusion about a population based on sample size and makes a generalization about the entire population
  
  # Descriptive Statistics is used to summarizes a data.it also summarizes the sample size. for DS, we have Measure of Central Tendency, Measure of Dispersion

In [3]:
# Measure pf Central Tendency
# Mean, Median and Mode

import math
import numpy as np
Age = [23,24,25,26,29,30]

In [5]:
np.mean(Age)

26.166666666666668

In [6]:
mean_age = round(np.mean(Age),0)

In [7]:
mean_age

26.0

In [18]:
# Data Showing the population age of People living Berger
population_age = [12,14,15,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,13,12,14,12,15,16,18,20,21,22,23,24,25,30,30,30,40,44,46,48,48,34,34,35,36,37,38,12,13,50,51,52,53,54,56,57,58,59,40,41,43,45,47,49,31,33,35,37,39,61,63,65,67,69]

In [14]:
a= len(population_age)
print(a)

100


In [15]:
np.mean(population_age)

45.8

In [17]:
popnAge = round(np.mean(population_age),0)

popnAge

46.0

# From the population of Age of people living in Berger
- we observed that the average age of 46.0 of the population belongs to active labour force. They are the age of active services

In [20]:
AM = round(np.median(population_age),0)

AM

44.0

In [25]:
# If a set of students are given a test to ascertaijn their typing speed as follows
typingSpeed = [2,3,5,6,7,1,4,9,2,4,3,1,9,7,6,5,3,4]


In [26]:
MedianAge = round(np.median(typingSpeed),0)
MedianAge

4.0

# TO SUMMARIZE THE DATA ABOVE
- The  Above data shows that students that finished typing before the median value 4 are fast typers 
- students that finished at 4.0 can be described as medium typers
- FInally students that finished after the median Value 4 are slow typers

In [31]:
# Mode shows the value with the highest reoccurrence i.e. The number that came out more out a data
userId = [202,202,203,204,205,206,206,207,206,208,209,210,211,202,205]

In [29]:
import statistics as st

In [30]:
st.mode(userId)

202

In [32]:
# Find the following: Mean, Median, Mode from the data below:

unitPrice =[500,400,300,200,100,500,500,600,300,150,500,650,700,380]

In [36]:
# Mean
MeanPrice = round(np.mean(unitPrice),0)
MeanPrice

413.0

In [37]:
# Median
MedianPrice = round(np.median(unitPrice),0)
MedianPrice

450.0

In [38]:
# Mode
st.mode(unitPrice)

500

# Measure Of Dispersion
- Range: shows how spread the data is, by calculating the difference between the highest and the lowest

In [39]:
A = [250,340,500,600,780,800,1000,3780,200]

In [45]:
import statistics as st
import numpy as np

range_a = np.ptp(A)

In [46]:
range_a

3580

In [47]:
# Find the range of the population age of the people living in Berger
population_age = [12,14,15,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,13,12,14,12,15,16,18,20,21,22,23,24,25,30,30,30,40,44,46,48,48,34,34,35,36,37,38,12,13,50,51,52,53,54,56,57,58,59,40,41,43,45,47,49,31,33,35,37,39,61,63,65,67,69]

In [48]:
range_age = np.ptp(population_age)
range_age

88

# Interquartile Range
- Unlike median that divides the data into 2 parts, quantile divides the data set into four parts.
- Quantile deals with value from 0 to 1 i.e. 0.25, 0.50, 0.75 to 1 while Percentile starts from 1 to 100 like 25,50,75,100

In [72]:
# Quartile Exercise
totalPrice = [20,40,30,35,50,34,40,50,55,56,58,60,70,80,90,56,43,18,19,21]

In [52]:
# For First Quantile, we have: 
q1 = np.quantile(totalPrice, 0.25)

In [51]:
q1

33.0

In [55]:
# For Second Quantile, we have:
q2 = np.quantile(totalPrice,0.50)

In [56]:
q2

46.5

In [57]:
# For Third Quantile, we have:
q3 = np.quantile(totalPrice, 0.75)
q3

56.5

In [58]:
# For Fourth Quantile, we have:
q4 = np.quantile(totalPrice, 1)
q4

90

In [61]:
# Percentile Exercise
totalRevenue = [2500,3000,4500,5000,5500,6000,6500,7000,7500,8000,8500,9000,9500,10000,2600,2700,2800,2900,3100,3200]

In [68]:
# For First Percentile, we have:
p1 = np.percentile(totalRevenue,25)

In [63]:
p1

2975.0

In [69]:
# For Second Percentile, we have:
p2 = np.percentile(totalRevenue,50)

In [65]:
p2

5250.0

In [70]:
# FOr Third Percentile, we have:
p3 = np.percentile(totalRevenue,75)
p3

7625.0

In [71]:
# For Fourth, percentile, we have:
p4 = np.percentile(totalRevenue,100)
p4

10000.0

# Interquantile range (IRQ): gives the difference between third quantile and first quantile, It helps us to see how clustered our data is
- IRQ = Q3 - Q1
- Range observes the overview of the entire data while the interquantile range observes the overview of half the data set
- Interquantile range helps to know how clustered a particular data set is.

In [74]:
# From the data below, calculate the interquantile range:
age = [25,50,60,62,64,65,66,67,68,69,70,72,74,76,78,80,82,84,86,88,90,92,93,94,96,98,100,10,12,13,14,15,16,17,18,19,20]

In [76]:
Q3 = np.quantile(age, 0.75)
Q3

84.0

In [77]:
Q1 = np.quantile(age, 0.25)
Q1

20.0

In [79]:
IQR = Q3 - Q1
IQR

64.0

# To find the outliers within the data set
- counts + Q3: any number above value will be refered to upper outlier
- counts - Q1: any number or numbers below this value will be lower outlier(s)

In [81]:
counts = IQR * 1.5

counts

96.0

In [96]:
# To calculate the higher outlier where counts = 96.0 and Q3 = 84.0
upper = counts + Q3
upper

180.0

In [90]:
# To calculate for lower outlier where counts = 96.0 and Q1 = 20.0
lower = counts - Q1
lower

76.0

In [88]:
arr = np.array(age)

arr

array([ 25,  50,  60,  62,  64,  65,  66,  67,  68,  69,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  93,  94,  96,  98,
       100,  10,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [93]:
lower_outlier = arr[arr<lower]
lower_outlier

array([25, 50, 60, 62, 64, 65, 66, 67, 68, 69, 70, 72, 74, 10, 12, 13, 14,
       15, 16, 17, 18, 19, 20])

In [94]:
len_outlier = len(lower_outlier)
print("The total number of lower outlier in the dataset is", len_outlier)

The total number of lower outlier in the dataset is 23


In [99]:
# To check for the upper outlier
upper_outlier = arr[arr>upper]
upper_outlier

array([], dtype=int32)

In [103]:
exam_score =[61,62,63,64,65,66,67,68,69,70,33,34,35,36,50,55,56,57,58,59,60,63,66,69,70,71,72,73,74,75,76,77,78,79,80,40,41,42,43,43,44,45,46,47,48,49,50,30,31,32,33,34,35,36,37,38,39,40,50,51,52,53,54,55,56,57,58,59,60,20,21,22,23,24,25,26,27,28,29,30,10,11,12,13,14,15,26,17,18,19,20,120,130,140,150,160,170,180,190,200]

In [104]:
len(exam_score)

100

# Class Exercise
- Find the number of students that scored below the first quantile
- Find the students that scored above q3
- Determine if the data has upper outlier and lower outlier

In [107]:
Q1 = np.quantile(exam_score,0.25)
Q1

32.75

In [108]:
Q3 = np.quantile(exam_score, 0.75)
Q3

66.25

In [109]:
IQR = Q3 - Q1
IQR

33.5

In [110]:
exam_count= IQR * 1.5
exam_count

50.25

In [112]:
upper_exam = exam_count + Q3
upper_exam

116.5

In [115]:
lower_exam = exam_count - Q1
lower_exam

17.5

In [118]:
arr1= np.array(exam_score)
arr1

array([ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  33,  34,  35,
        36,  50,  55,  56,  57,  58,  59,  60,  63,  66,  69,  70,  71,
        72,  73,  74,  75,  76,  77,  78,  79,  80,  40,  41,  42,  43,
        43,  44,  45,  46,  47,  48,  49,  50,  30,  31,  32,  33,  34,
        35,  36,  37,  38,  39,  40,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  10,  11,  12,  13,  14,  15,  26,  17,  18,  19,  20,
       120, 130, 140, 150, 160, 170, 180, 190, 200])

In [130]:
# Question 1... STudents that scored below Q1
below_Q1 = arr1[arr1<Q1]
below_Q1
print("The Number of Students that scored below the Q1 is", len(below_Q1), "and their Exam Scores are", below_Q1)

The Number of Students that scored below the Q1 is 25 and their Exam Scores are [30 31 32 20 21 22 23 24 25 26 27 28 29 30 10 11 12 13 14 15 26 17 18 19
 20]


In [132]:
# Question 2... Students that scored below Q3
above_Q3 = arr1[arr1>Q3]
above_Q3
print("The number of students that score above Q3 is", len(above_Q3), "and their Exam Scores are", above_Q3)

The number of students that score above Q3 is 25 and their Exam Scores are [ 67  68  69  70  69  70  71  72  73  74  75  76  77  78  79  80 120 130
 140 150 160 170 180 190 200]


In [122]:
# Question 3.. Upper Outlier
upper_Outlier = arr1[arr1>upper_exam]
upper_Outlier

array([120, 130, 140, 150, 160, 170, 180, 190, 200])

In [126]:
len_E = len(upper_Outlier)
print("The Total Number of Upper Outlier in the Exam Score is", len_E, "and they are", upper_Outlier)

The Total Number of Upper Outlier in the Exam Score is 9 and they are [120 130 140 150 160 170 180 190 200]


In [133]:
# Question 3: Lower Outlier
lower_outlier = arr1[arr1<lower_exam]
lower_outlier

array([10, 11, 12, 13, 14, 15, 17])

In [127]:
len_E2= len(lower_outlier)
print("The Total Number of Lower Outlier in the Exam Score is", len_E2, "and they are", lower_outlier)

The Total Number of Lower Outlier in the Exam Score is 7 and they are [10 11 12 13 14 15 17]
